global:
  resolve_timeout: 5m
  slack_api_url: "https://hooks.slack.com/services/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"
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 2m
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        channel: "#flask-prometheus-grafana"
        text: "Alert!"
        title: "{{.CommonAnnotations.summary}}"
